{
 "title": "Powerwall Power Flow",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "grid_cost", "label": "Grid Cost", "query": "0.135" },
   {
    "name": "powerwall",
    "label": "Powerwall",
    "query": "from(bucket: \"powerwall\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http\")\n  |> keep(columns: [\"host\"])\n  |> unique(column: \"host\")\n  |> map(fn: (r) => ({ \n    \"_value\": r.host\n  }))"
   }
  ]
 },
 "panels": [
  { "title": "Live Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Energy Usage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "target": [ "sun_altitude" ] },
    {
     "query": "from(bucket: \"powerwall\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"instant_power\")\n  |> filter(fn: (r) => r[\"_field\"] == \"home\")\n  |> filter(fn: (r) => r[\"host\"] == \"${powerwall}\")\n  |> set(key: \"_field\", value: \"Home Usage\")"
    },
    {
     "query": "from(bucket: \"powerwall\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"instant_power\")\n  |> filter(fn: (r) => r[\"_field\"] == \"solar\")\n  |> filter(fn: (r) => r[\"host\"] == \"${powerwall}\")\n  |> set(key: \"_field\", value: \"Solar Energy\")"
    },
    {
     "query": "from(bucket: \"powerwall\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"instant_power\")\n  |> filter(fn: (r) => r[\"_field\"] == \"battery\")\n  |> filter(fn: (r) => r[\"host\"] == \"${powerwall}\")\n  |> set(key: \"_field\", value: \"Powerwall\")"
    },
    {
     "query": "from(bucket: \"powerwall\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"instant_power\")\n  |> filter(fn: (r) => r[\"_field\"] == \"grid\")\n  |> filter(fn: (r) => r[\"host\"] == \"${powerwall}\")\n  |> set(key: \"_field\", value: \"Grid Usage\")"
    },
    {
     "query": "from(bucket: \"powerwall\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"instant_power\")\n  |> filter(fn: (r) => r[\"_field\"] == \"percentage\")\n  |> filter(fn: (r) => r[\"host\"] == \"${powerwall}\")\n  |> set(key: \"_field\", value: \"Charge\")"
    },
    {
     "query": "from(bucket: \"powerwall\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"instant_power\")\n  |> filter(fn: (r) => r[\"_field\"] == \"grid_status\")\n  |> filter(fn: (r) => r[\"host\"] == \"${powerwall}\")\n  |> filter(fn: (r) => r[\"_value\"] == 0)\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> set(key: \"_field\", value: \"Grid Down\")"
    },
    {
     "query": "from(bucket: \"powerwall\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"weather\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\n  |> filter(fn: (r) => r[\"forecast\"] == \"*\")\n  |> keep(columns: [\"_field\", \"_value\", \"_time\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> set(key: \"_field\", value: \"Temperature\")"
    },
    {
     "query": "from(bucket: \"powerwall\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"weather\")\n  |> filter(fn: (r) => r[\"_field\"] == \"cloudiness\")\n  |> filter(fn: (r) => r[\"forecast\"] == \"*\")\n  |> keep(columns: [\"_field\", \"_value\", \"_time\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> set(key: \"_field\", value: \"Clouds\")"
    },
    {
     "query": "from(bucket: \"powerwall\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"weather\")\n  |> filter(fn: (r) => r[\"_field\"] == \"feels_like\")\n  |> filter(fn: (r) => r[\"forecast\"] == \"*\")\n  |> keep(columns: [\"_field\", \"_value\", \"_time\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> set(key: \"_field\", value: \"Feels Like\")"
    }
   ]
  },
  { "title": "Power Meters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Home Usage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "measurement": "http",
     "query": "from(bucket: \"powerwall\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"instant_power\")\n  |> filter(fn: (r) => r[\"_field\"] == \"home\")\n  |> filter(fn: (r) => r[\"host\"] == \"${powerwall}\")\n  |> integral(column: \"_value\")\n  |> map(fn: (r) => ({ r with _value: r._value / 1000.0 / 3600.0 }))",
     "select": [
      [
       { "params": [ "home" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 1000 / 3600" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Solar Energy",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "measurement": "http",
     "query": "from(bucket: \"powerwall\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"instant_power\")\n  |> filter(fn: (r) => r[\"_field\"] == \"solar\")\n  |> filter(fn: (r) => r[\"host\"] == \"${powerwall}\")\n  |> integral(column: \"_value\")\n  |> map(fn: (r) => ({ r with _value: r._value / 1000.0 / 3600.0 }))",
     "select": [
      [
       { "params": [ "solar" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 1000 / 3600" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "To Powerwall",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "measurement": "http",
     "query": "from(bucket: \"powerwall\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"instant_power\")\n  |> filter(fn: (r) => r[\"_field\"] == \"to_powerwall\")\n  |> filter(fn: (r) => r[\"host\"] == \"${powerwall}\")\n  |> integral(column: \"_value\")\n  |> map(fn: (r) => ({ r with _value: r._value / 1000.0 / 3600.0 }))",
     "select": [
      [
       { "params": [ "to_pw" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 1000 / 3600" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "From Powerwall",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "measurement": "http",
     "query": "from(bucket: \"powerwall\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"instant_power\")\n  |> filter(fn: (r) => r[\"_field\"] == \"from_powerwall\")\n  |> filter(fn: (r) => r[\"host\"] == \"${powerwall}\")\n  |> integral(column: \"_value\")\n  |> map(fn: (r) => ({ r with _value: r._value / 1000.0 / 3600.0 }))",
     "select": [
      [
       { "params": [ "from_pw" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 1000 / 3600" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "To Grid",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "measurement": "http",
     "query": "from(bucket: \"powerwall\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"instant_power\")\n  |> filter(fn: (r) => r[\"_field\"] == \"to_grid\")\n  |> filter(fn: (r) => r[\"host\"] == \"${powerwall}\")\n  |> integral(column: \"_value\")\n  |> map(fn: (r) => ({ r with _value: r._value / 1000.0 / 3600.0 }))",
     "select": [
      [
       { "params": [ "to_grid" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 1000 / 3600" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "From Grid",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "measurement": "http",
     "query": "from(bucket: \"powerwall\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"instant_power\")\n  |> filter(fn: (r) => r[\"_field\"] == \"from_grid\")\n  |> filter(fn: (r) => r[\"host\"] == \"${powerwall}\")\n  |> integral(column: \"_value\")\n  |> map(fn: (r) => ({ r with _value: r._value / 1000.0 / 3600.0 }))",
     "select": [
      [
       { "params": [ "from_grid" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 1000 / 3600" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Savings",
   "type": "graph",
   "description": "Estimated Savings",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "alias": "powerwall > home",
     "query": "from(bucket: \"powerwall\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kwh\")\n  |> filter(fn: (r) => r[\"_field\"] == \"from_powerwall\")\n  |> filter(fn: (r) => r[\"host\"] == \"${powerwall}\")\n  |> sum()\n  |> map(fn: (r) => ({ r with _value: r._value * ${grid_cost} }))\n  |> keep(columns: [\"_value\", \"_stop\"])\n  |> map(fn: (r) => ({ \n    \"_time\": r._stop,\n    \"_field\": \"powerwall > home\",\n    \"_value\": r._value\n  }))\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")"
    },
    {
     "query": "from(bucket: \"powerwall\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kwh\")\n  |> filter(fn: (r) => r[\"_field\"] == \"to_powerwall\" or r[\"_field\"] == \"to_grid\" or r[\"_field\"] == \"solar\")\n  |> filter(fn: (r) => r[\"host\"] == \"${powerwall}\")\n  |> sum()\n  |> map(fn: (r) => ({ r with _value: r._value * ${grid_cost} }))\n  |> keep(columns: [\"_field\", \"_value\", \"_stop\"])\n  |> pivot(rowKey:[\"_stop\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ \n    \"_time\": r._stop,\n    \"solar > home\": r.solar - (r.to_powerwall + r.to_grid)\n  }))"
    },
    {
     "query": "from(bucket: \"powerwall\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kwh\")\n  |> filter(fn: (r) => r[\"_field\"] == \"to_grid\")\n  |> filter(fn: (r) => r[\"host\"] == \"${powerwall}\")\n  |> sum()\n  |> map(fn: (r) => ({ r with _value: r._value * ${grid_cost} }))\n  |> keep(columns: [\"_value\", \"_stop\"])\n  |> map(fn: (r) => ({ \n    \"_time\": r._stop,\n    \"_field\": \"solar > grid\",\n    \"_value\": r._value\n  }))\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")"
    },
    {
     "query": "from(bucket: \"powerwall\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kwh\")\n  |> filter(fn: (r) => r[\"_field\"] == \"to_powerwall\" or r[\"_field\"] == \"to_grid\" or r[\"_field\"] == \"solar\" or r[\"_field\"] == \"from_powerwall\")\n  |> filter(fn: (r) => r[\"host\"] == \"${powerwall}\")\n  |> sum()\n  |> map(fn: (r) => ({ r with _value: r._value * ${grid_cost} }))\n  |> keep(columns: [\"_field\", \"_value\", \"_stop\"])\n  |> pivot(rowKey:[\"_stop\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ \n    \"_time\": r._stop,\n    \"total\": r.to_grid + (r.solar - r.to_powerwall - r.to_grid) + r.from_powerwall\n  }))"
    }
   ]
  },
  {
   "title": "Self-Powered",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 8, "x": 9, "y": 17 },
   "format": "kwatth",
   "valueName": "total",
   "targets": [
    {
     "alias": "From Powerwall",
     "measurement": "http",
     "query": "from(bucket: \"powerwall\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"instant_power\")\n  |> filter(fn: (r) => r[\"_field\"] == \"from_powerwall\")\n  |> filter(fn: (r) => r[\"host\"] == \"${powerwall}\")\n  |> integral(column: \"_value\")\n  |> keep(columns: [\"_value\", \"_stop\"])\n  |> map(fn: (r) => ({ \n    \"_time\": r._stop,\n    \"_field\": \"From Powerwall\",\n    \"_value\": r._value / 1000.0 / 3600.0\n  }))\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")",
     "select": [
      [
       { "params": [ "from_pw" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 1000 / 3600" ], "type": "math" }
      ]
     ],
     "tz": "America/Los_Angeles"
    },
    {
     "query": "from(bucket: \"powerwall\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"instant_power\")\n  |> filter(fn: (r) => r[\"_field\"] == \"from_grid\")\n  |> filter(fn: (r) => r[\"host\"] == \"${powerwall}\")\n  |> integral(column: \"_value\")\n  |> keep(columns: [\"_value\", \"_stop\"])\n  |> map(fn: (r) => ({ \n    \"_time\": r._stop,\n    \"_field\": \"From Grid\",\n    \"_value\": r._value / 1000.0 / 3600.0\n  }))\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")"
    },
    {
     "query": "from(bucket: \"powerwall\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"instant_power\")\n  |> filter(fn: (r) => r[\"_field\"] == \"solar\")\n  |> filter(fn: (r) => r[\"host\"] == \"${powerwall}\")\n  |> integral(column: \"_value\")\n  |> keep(columns: [\"_value\", \"_stop\"])\n  |> map(fn: (r) => ({ \n    \"_time\": r._stop,\n    \"_field\": \"From Solar\",\n    \"_value\": r._value / 1000.0 / 3600.0\n  }))\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")"
    }
   ]
  },
  {
   "title": "Current State",
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 17 },
   "targets": [
    {
     "query": "import \"strings\"\nfrom(bucket: \"powerwall\")\n  |> range(start: -10m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"instant_power\")\n  |> filter(fn: (r) => r[\"_field\"] == \"solar\" or r[\"_field\"] == \"home\" or r[\"_field\"] == \"battery\" or r[\"_field\"] == \"grid\")\n  |> filter(fn: (r) => r[\"host\"] == \"${powerwall}\")\n  |> last()\n  |> map(fn: (r) => ({ \n    \"_time\": r._time,\n    \"_field\": strings.title(v: r._field),\n    \"_value\": r._value / 1000.0\n  }))\n  "
    }
   ]
  },
  { "title": "Monthly Analysis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Home Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "alias": "Home Usage",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "import \"timezone\"\nimport \"date\"\n\noption location = timezone.location(name: \"America/New_York\")\n\nfrom(bucket: \"powerwall\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kwh\")\n  |> filter(fn: (r) => r[\"_field\"] == \"home\")\n  |> filter(fn: (r) => r[\"host\"] == \"${powerwall}\")\n  |> map(fn: (r) => ({r with _time: date.truncate(t: r._time, unit: 1d )}))\n  |> group(columns: [\"_time\", \"_field\", \"_host\"])\n  |> sum(column: \"_value\")\n  |> group(columns: [\"_field\"])\n  |> set(key: \"_field\", value: \"Home Usage\")",
     "select": [
      [
       { "params": [ "home" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tz": "America/Los_Angeles"
    }
   ]
  },
  {
   "title": "Solar Energy",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "alias": "Solar Energy",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "import \"timezone\"\nimport \"date\"\n\noption location = timezone.location(name: \"America/New_York\")\n\nfrom(bucket: \"powerwall\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kwh\")\n  |> filter(fn: (r) => r[\"_field\"] == \"solar\")\n  |> filter(fn: (r) => r[\"host\"] == \"${powerwall}\")\n  |> map(fn: (r) => ({r with _time: date.truncate(t: r._time, unit: 1d )}))\n  |> group(columns: [\"_time\", \"_field\", \"_host\"])\n  |> sum(column: \"_value\")\n  |> group(columns: [\"_field\"])\n  |> set(key: \"_field\", value: \"Solar Energy\")",
     "select": [
      [
       { "params": [ "solar" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "solar", "operator": ">", "value": "0" }
     ],
     "tz": "America/Los_Angeles"
    }
   ]
  },
  {
   "title": "Powerwall",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "alias": "From Powerwall",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "import \"timezone\"\nimport \"date\"\n\noption location = timezone.location(name: \"America/New_York\")\n\nfrom(bucket: \"powerwall\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kwh\")\n  |> filter(fn: (r) => r[\"_field\"] == \"from_powerwall\")\n  |> filter(fn: (r) => r[\"host\"] == \"${powerwall}\")\n  |> map(fn: (r) => ({r with _time: date.truncate(t: r._time, unit: 1d )}))\n  |> group(columns: [\"_time\", \"_field\", \"_host\"])\n  |> sum(column: \"_value\")\n  |> group(columns: [\"_field\"])\n  |> set(key: \"_field\", value: \"From Powerwall\")",
     "select": [
      [
       { "params": [ "from_pw" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tz": "America/Los_Angeles"
    },
    {
     "query": "import \"timezone\"\nimport \"date\"\n\noption location = timezone.location(name: \"America/New_York\")\n\nfrom(bucket: \"powerwall\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kwh\")\n  |> filter(fn: (r) => r[\"_field\"] == \"to_powerwall\")\n  |> filter(fn: (r) => r[\"host\"] == \"${powerwall}\")\n  |> map(fn: (r) => ({r with _time: date.truncate(t: r._time, unit: 1d )}))\n  |> group(columns: [\"_time\", \"_field\", \"_host\"])\n  |> sum(column: \"_value\")\n  |> group(columns: [\"_field\"])\n  |> set(key: \"_field\", value: \"To Powerwall\")"
    }
   ]
  },
  {
   "title": "Grid Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "alias": "From Grid",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "import \"timezone\"\nimport \"date\"\n\noption location = timezone.location(name: \"America/New_York\")\n\nfrom(bucket: \"powerwall\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kwh\")\n  |> filter(fn: (r) => r[\"_field\"] == \"from_grid\")\n  |> filter(fn: (r) => r[\"host\"] == \"${powerwall}\")\n  |> map(fn: (r) => ({r with _time: date.truncate(t: r._time, unit: 1d )}))\n  |> group(columns: [\"_time\", \"_field\", \"_host\"])\n  |> sum(column: \"_value\")\n  |> group(columns: [\"_field\"])\n  |> set(key: \"_field\", value: \"From Grid\")",
     "select": [
      [
       { "params": [ "from_grid" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tz": "America/Los_Angeles"
    },
    {
     "alias": "To Grid",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "import \"timezone\"\nimport \"date\"\n\noption location = timezone.location(name: \"America/New_York\")\n\nfrom(bucket: \"powerwall\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kwh\")\n  |> filter(fn: (r) => r[\"_field\"] == \"to_grid\")\n  |> filter(fn: (r) => r[\"host\"] == \"${powerwall}\")\n  |> map(fn: (r) => ({r with _time: date.truncate(t: r._time, unit: 1d )}))\n  |> group(columns: [\"_time\", \"_field\", \"_host\"])\n  |> sum(column: \"_value\")\n  |> group(columns: [\"_field\"])\n  |> set(key: \"_field\", value: \"To Grid\")",
     "select": [
      [
       { "params": [ "to_grid" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "* -1" ], "type": "math" }
      ]
     ],
     "tz": "America/Los_Angeles"
    }
   ]
  },
  {
   "title": "Solar Energy Year",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "alias": "Solar Energy",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "import \"timezone\"\nimport \"date\"\n\noption location = timezone.location(name: \"America/New_York\")\n\nfrom(bucket: \"powerwall\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kwh\")\n  |> filter(fn: (r) => r[\"_field\"] == \"home\")\n  |> filter(fn: (r) => r[\"host\"] == \"${powerwall}\")\n  |> map(fn: (r) => ({r with _time: date.truncate(t: r._time, unit: 1d )}))\n  |> group(columns: [\"_time\", \"_field\", \"_host\"])\n  |> sum(column: \"_value\")\n  |> group(columns: [\"_field\"])\n  |> set(key: \"_field\", value: \"Home Usage\")",
     "select": [
      [
       { "params": [ "solar" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "solar", "operator": ">", "value": "0" }
     ],
     "tz": "America/Los_Angeles"
    },
    {
     "alias": "Home Usage",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "import \"timezone\"\nimport \"date\"\n\noption location = timezone.location(name: \"America/New_York\")\n\nfrom(bucket: \"powerwall\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kwh\")\n  |> filter(fn: (r) => r[\"_field\"] == \"solar\")\n  |> filter(fn: (r) => r[\"host\"] == \"${powerwall}\")\n  |> map(fn: (r) => ({r with _time: date.truncate(t: r._time, unit: 1d )}))\n  |> group(columns: [\"_time\", \"_field\", \"_host\"])\n  |> sum(column: \"_value\")\n  |> group(columns: [\"_field\"])\n  |> set(key: \"_field\", value: \"Solar Energy\")",
     "select": [
      [
       { "params": [ "home" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "home", "operator": ">", "value": "0" }
     ],
     "tz": "America/Los_Angeles"
    },
    {
     "query": "import \"timezone\"\nimport \"date\"\n\noption location = timezone.location(name: \"America/New_York\")\n\nfrom(bucket: \"powerwall\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kwh\")\n  |> filter(fn: (r) => r[\"_field\"] == \"to_grid\")\n  |> filter(fn: (r) => r[\"host\"] == \"${powerwall}\")\n  |> map(fn: (r) => ({r with _time: date.truncate(t: r._time, unit: 1d )}))\n  |> group(columns: [\"_time\", \"_field\", \"_host\"])\n  |> sum(column: \"_value\")\n  |> group(columns: [\"_field\"])\n  |> set(key: \"_field\", value: \"To Grid\")"
    }
   ]
  },
  {
   "title": "Powerwall+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "String Voltage",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "volt" }
     ],
     "targets": [
      {
       "query": "import \"regexp\"\nfrom(bucket: \"powerwall\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"plus\")\n  |> filter(fn: (r) => r[\"_field\"] == \"string_volt_D\" or r[\"_field\"] == \"string_volt_C\" or r[\"_field\"] == \"string_volt_B\" or r[\"_field\"] == \"string_volt_A\" or r[\"_field\"] == \"string_volt_D1\" or r[\"_field\"] == \"string_volt_C1\" or r[\"_field\"] == \"string_volt_B1\" or r[\"_field\"] == \"string_volt_A1\" or r[\"_field\"] == \"string_volt_D2\" or r[\"_field\"] == \"string_volt_C2\" or r[\"_field\"] == \"string_volt_B2\" or r[\"_field\"] == \"string_volt_A2\" or r[\"_field\"] == \"string_volt_D3\" or r[\"_field\"] == \"string_volt_C3\" or r[\"_field\"] == \"string_volt_B3\" or r[\"_field\"] == \"string_volt_A3\")\n  |> filter(fn: (r) => r[\"host\"] == \"${powerwall}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({ r with _field: regexp.replaceAllString(v: r._field, r: /string_volt_([A-D][1-3]?)/, t: \"$1\") }))"
      }
     ]
    },
    {
     "title": "String Current",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "amp" } },
     "yaxes": [
      { "format": "amp" }
     ],
     "targets": [
      {
       "query": "import \"regexp\"\nfrom(bucket: \"powerwall\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"plus\")\n  |> filter(fn: (r) => r[\"_field\"] == \"string_current_D\" or r[\"_field\"] == \"string_current_C\" or r[\"_field\"] == \"string_current_B\" or r[\"_field\"] == \"string_current_A\" or r[\"_field\"] == \"string_current_D1\" or r[\"_field\"] == \"string_current_C1\" or r[\"_field\"] == \"string_current_B1\" or r[\"_field\"] == \"string_current_A1\" or r[\"_field\"] == \"string_current_D2\" or r[\"_field\"] == \"string_current_C2\" or r[\"_field\"] == \"string_current_B2\" or r[\"_field\"] == \"string_current_A2\" or r[\"_field\"] == \"string_current_D3\" or r[\"_field\"] == \"string_current_C3\" or r[\"_field\"] == \"string_current_B3\" or r[\"_field\"] == \"string_current_A3\")\n  |> filter(fn: (r) => r[\"host\"] == \"${powerwall}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({ r with _field: regexp.replaceAllString(v: r._field, r: /string_current_([A-D][1-3]?)/, t: \"$1\") }))"
      }
     ]
    },
    {
     "title": "String Power",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "yaxes": [
      { "format": "watt" }
     ],
     "targets": [
      {
       "query": "import \"regexp\"\nfrom(bucket: \"powerwall\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"plus\")\n  |> filter(fn: (r) => r[\"_field\"] == \"string_power_D\" or r[\"_field\"] == \"string_power_C\" or r[\"_field\"] == \"string_power_B\" or r[\"_field\"] == \"string_power_A\" or r[\"_field\"] == \"string_power_D1\" or r[\"_field\"] == \"string_power_C1\" or r[\"_field\"] == \"string_power_B1\" or r[\"_field\"] == \"string_power_A1\" or r[\"_field\"] == \"string_power_D2\" or r[\"_field\"] == \"string_power_C2\" or r[\"_field\"] == \"string_power_B2\" or r[\"_field\"] == \"string_power_A2\" or r[\"_field\"] == \"string_power_D3\" or r[\"_field\"] == \"string_power_C3\" or r[\"_field\"] == \"string_power_B3\" or r[\"_field\"] == \"string_power_A3\")\n  |> filter(fn: (r) => r[\"host\"] == \"${powerwall}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({ r with _field: regexp.replaceAllString(v: r._field, r: /string_power_([A-D][1-3]?)/, t: \"$1\") }))"
      }
     ]
    },
    {
     "title": "Inverter Power",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "watt" }
     ],
     "targets": [
      {
       "alias": "Inverter1",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "http",
       "query": "import \"strings\"\nfrom(bucket: \"powerwall\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"plus\")\n  |> filter(fn: (r) => r[\"_field\"] == \"inverter\" or r[\"_field\"] == \"inverter1\" or r[\"_field\"] == \"inverter2\" or r[\"_field\"] == \"inverter3\")\n  |> filter(fn: (r) => r[\"host\"] == \"${powerwall}\")\n  |> map(fn: (r) => ({ r with _field: strings.title(v: r._field) }))\n\n",
       "select": [
        [
         { "params": [ "Inverter1" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Powerwall Temps ",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 51 },
     "yaxes": [
      { "format": "celsius" }
     ],
     "targets": [
      {
       "alias": "Powerwall1",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "http",
       "query": "import \"strings\"\nfrom(bucket: \"powerwall\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"plus\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temp_PW1\"  or r[\"_field\"] == \"temp_PW2\"  or r[\"_field\"] == \"temp_PW3\"  or r[\"_field\"] == \"temp_PW4\"  or r[\"_field\"] == \"temp_PW5\"  or r[\"_field\"] == \"temp_PW6\" or r[\"_field\"] == \"temp_PW7\" or r[\"_field\"] == \"temp_PW8\")\n  |> filter(fn: (r) => r[\"host\"] == \"${powerwall}\")\n  |> map(fn: (r) => ({ r with _field: strings.replace(v: r._field, t: \"temp_\", u: \"\", i: 1) }))  ",
       "select": [
        [
         { "params": [ "PW1_temp" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Frequency",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 57 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "alias": "Home L1",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "http",
       "query": "import \"strings\"\nfrom(bucket: \"powerwall\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"plus\")\n  |> filter(fn: (r) => r[\"_field\"] == \"freq_home_L1\" or r[\"_field\"] == \"freq_home_L2\" or r[\"_field\"] == \"freq_home_L3\" or r[\"_field\"] == \"freq_grid_L1\" or r[\"_field\"] == \"freq_grid_L2\" or r[\"_field\"] == \"freq_grid_L3\" or r[\"_field\"] == \"freq_PW1\" or r[\"_field\"] == \"freq_PW2\" or r[\"_field\"] == \"freq_PW3\" or r[\"_field\"] == \"freq_PW4\" or r[\"_field\"] == \"freq_PW5\" or r[\"_field\"] == \"freq_PW6\" or r[\"_field\"] == \"freq_PW7\" or r[\"_field\"] == \"freq_PW8\")\n  |> filter(fn: (r) => r[\"host\"] == \"${powerwall}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({ r with _field: strings.title(v: strings.replace(v: strings.replace(v: r._field, t: \"freq_\", u: \"\", i: 1), t: \"_\", u: \" \", i: 1)) }))",
       "select": [
        [
         { "params": [ "ISLAND_FreqL1_Load" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Voltages",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "yaxes": [
      { "format": "volt" }
     ],
     "targets": [
      {
       "alias": "Home L1",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "http",
       "query": "import \"strings\"\nfrom(bucket: \"powerwall\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"plus\")\n  |> filter(fn: (r) => r[\"_field\"] == \"volt_PW1_L1\"  or r[\"_field\"] == \"volt_PW2_L1\"  or r[\"_field\"] == \"volt_PW3_L1\"  or r[\"_field\"] == \"volt_PW4_L1\"  or r[\"_field\"] == \"volt_PW5_L1\"  or r[\"_field\"] == \"volt_PW6_L1\" or r[\"_field\"] == \"volt_PW7_L1\" or r[\"_field\"] == \"volt_PW8_L1\" or r[\"_field\"] == \"volt_PW1_L2\"  or r[\"_field\"] == \"volt_PW2_L2\" or r[\"_field\"] == \"volt_PW3_L2\"  or r[\"_field\"] == \"volt_PW4_L2\"  or r[\"_field\"] == \"volt_PW5_L2\"  or r[\"_field\"] == \"volt_PW6_L2\" or r[\"_field\"] == \"volt_PW7_L2\" or r[\"_field\"] == \"volt_PW8_L2\" or r[\"_field\"] == \"volt_PW1_L3\"  or r[\"_field\"] == \"volt_PW2_L3\"  or r[\"_field\"] == \"volt_PW3_L3\"  or r[\"_field\"] == \"volt_PW4_L3\"  or r[\"_field\"] == \"volt_PW5_L3\"  or r[\"_field\"] == \"volt_PW6_L3\" or r[\"_field\"] == \"volt_PW7_L3\" or r[\"_field\"] == \"volt_PW8_L3\" or r[\"_field\"] == \"volt_home_L1\"  or r[\"_field\"] == \"volt_home_L2\"  or r[\"_field\"] == \"volt_home_L3\"  or r[\"_field\"] == \"volt_grid_L1\"  or r[\"_field\"] == \"volt_grid_L2\"  or r[\"_field\"] == \"volt_grid_L3\" )\n  |> filter(fn: (r) => r[\"host\"] == \"${powerwall}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({ r with _field: strings.title(v: strings.replace(v: strings.replace(v: r._field, t: \"volt_\", u: \"\", i: 1), t: \"_\", u: \" \", i: 1)) }))",
       "select": [
        [
         { "params": [ "ISLAND_VL1N_Load" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Powerwall Capacity",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 67 },
     "yaxes": [
      { "format": "watth" }
     ],
     "targets": [
      {
       "alias": "PW1",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "http",
       "query": "import \"strings\"\nfrom(bucket: \"powerwall\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"plus\")\n  |> filter(fn: (r) => r[\"_field\"] == \"charge_capacity_PW1\"  or r[\"_field\"] == \"charge_capacity_PW2\"  or r[\"_field\"] == \"charge_capacity_PW3\"  or r[\"_field\"] == \"charge_capacity_PW4\"  or r[\"_field\"] == \"charge_capacity_PW5\"  or r[\"_field\"] == \"charge_capacity_PW6\" or r[\"_field\"] == \"charge_capacity_PW7\" or r[\"_field\"] == \"charge_capacity_PW8\")\n  |> filter(fn: (r) => r[\"host\"] == \"${powerwall}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({ r with _field: strings.replace(v: r._field, t: \"charge_capacity_\", u: \"\", i: 1) }))",
       "select": [
        [
         { "params": [ "PW1_POD_nom_full_pack_energy" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "PW2",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "http",
       "query": "import \"strings\"\nfrom(bucket: \"powerwall\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"plus\")\n  |> filter(fn: (r) => r[\"_field\"] == \"charge_remaining_PW1\"  or r[\"_field\"] == \"charge_remaining_PW2\"  or r[\"_field\"] == \"charge_remaining_PW3\"  or r[\"_field\"] == \"charge_remaining_PW4\"  or r[\"_field\"] == \"charge_remaining_PW5\"  or r[\"_field\"] == \"charge_remaining_PW6\" or r[\"_field\"] == \"charge_remaining_PW7\" or r[\"_field\"] == \"charge_remaining_PW8\")\n  |> filter(fn: (r) => r[\"host\"] == \"${powerwall}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({ r with _field: strings.replace(v: r._field, t: \"charge_remaining_\", u: \"\", i: 1) + \" Charge\" }))",
       "select": [
        [
         { "params": [ "PW2_POD_nom_full_pack_energy" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Weather",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperature, Humidity and Clouds",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "Temperature",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "weather",
       "query": "from(bucket: \"powerwall\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"weather\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\n  |> filter(fn: (r) => r[\"forecast\"] == \"*\")\n  |> keep(columns: [\"_field\", \"_value\", \"_time\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> set(key: \"_field\", value: \"Temperature\")",
       "select": [
        [
         { "params": [ "temperature" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Humidity (%)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "weather",
       "query": "from(bucket: \"powerwall\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"weather\")\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\")\n  |> filter(fn: (r) => r[\"forecast\"] == \"*\")\n  |> keep(columns: [\"_field\", \"_value\", \"_time\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> set(key: \"_field\", value: \"Humidity (%)\")",
       "select": [
        [
         { "params": [ "humidity" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Clouds (%)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "weather",
       "query": "from(bucket: \"powerwall\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"weather\")\n  |> filter(fn: (r) => r[\"_field\"] == \"cloudiness\")\n  |> filter(fn: (r) => r[\"forecast\"] == \"*\")\n  |> keep(columns: [\"_field\", \"_value\", \"_time\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> set(key: \"_field\", value: \"Clouds (%)\")",
       "select": [
        [
         { "params": [ "clouds" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Feels Like",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "weather",
       "query": "from(bucket: \"powerwall\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"weather\")\n  |> filter(fn: (r) => r[\"_field\"] == \"feels_like\")\n  |> filter(fn: (r) => r[\"forecast\"] == \"*\")\n  |> keep(columns: [\"_field\", \"_value\", \"_time\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> set(key: \"_field\", value: \"Feels Like\")",
       "select": [
        [
         { "params": [ "feels_like" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Wind, Pressure and Precipitation ",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "Snow",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "weather",
       "query": "from(bucket: \"powerwall\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"weather\")\n  |> filter(fn: (r) => r[\"_field\"] == \"wind_speed\")\n  |> filter(fn: (r) => r[\"forecast\"] == \"*\")\n  |> keep(columns: [\"_field\", \"_value\", \"_time\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> set(key: \"_field\", value: \"Wind\")",
       "select": [
        [
         { "params": [ "snow_1h" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Pressure",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "weather",
       "query": "from(bucket: \"powerwall\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"weather\")\n  |> filter(fn: (r) => r[\"_field\"] == \"visibility\")\n  |> filter(fn: (r) => r[\"forecast\"] == \"*\")\n  |> keep(columns: [\"_field\", \"_value\", \"_time\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({ r with _value: r._value / 1000.0 }))\n  |> set(key: \"_field\", value: \"Visibility (K)\")",
       "select": [
        [
         { "params": [ "pressure" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Rain",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "weather",
       "query": "from(bucket: \"powerwall\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"weather\")\n  |> filter(fn: (r) => r[\"_field\"] == \"rain\")\n  |> filter(fn: (r) => r[\"forecast\"] == \"*\")\n  |> keep(columns: [\"_field\", \"_value\", \"_time\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> set(key: \"_field\", value: \"Rain\")",
       "select": [
        [
         { "params": [ "rain_1h" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Visibility (K)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "weather",
       "query": "from(bucket: \"powerwall\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"weather\")\n  |> filter(fn: (r) => r[\"_field\"] == \"pressure\")\n  |> filter(fn: (r) => r[\"forecast\"] == \"*\")\n  |> keep(columns: [\"_field\", \"_value\", \"_time\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> set(key: \"_field\", value: \"Pressure\")",
       "select": [
        [
         { "params": [ "visibility" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ " / 1000" ], "type": "math" }
        ]
       ]
      },
      {
       "alias": "Wind",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "weather",
       "query": "from(bucket: \"powerwall\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"weather\")\n  |> filter(fn: (r) => r[\"_field\"] == \"snow\")\n  |> filter(fn: (r) => r[\"forecast\"] == \"*\")\n  |> keep(columns: [\"_field\", \"_value\", \"_time\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> set(key: \"_field\", value: \"Snow\")",
       "select": [
        [
         { "params": [ "wind_speed" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}